# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=100, verbose_name='\u7ebf\u8def\u7f16\u53f7')),
                ('line_local', models.CharField(max_length=255, verbose_name='\u672c\u5730\u5730\u5740')),
                ('line_speed', models.CharField(choices=[('2M', '2M'), ('10M', '10M'), ('100M', '100M')], default='10M', max_length=50, verbose_name='\u7ebf\u8def\u901f\u7387')),
                ('line_spname', models.CharField(choices=[('\u4e2d\u56fd\u7535\u4fe1', '\u4e2d\u56fd\u7535\u4fe1'), ('\u4e2d\u56fd\u8054\u901a', '\u4e2d\u56fd\u8054\u901a'), ('\u4e2d\u56fd\u79fb\u52a8', '\u4e2d\u56fd\u79fb\u52a8')], max_length=100, verbose_name='\u8fd0\u8425\u5546')),
                ('line_type', models.CharField(choices=[('MSTP', 'MSTP'), ('SDH', 'SDH')], default='MSTP', max_length=50, verbose_name='\u7ebf\u8def\u7c7b\u578b')),
                ('line_open', models.DateField(verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('line_signer', models.CharField(max_length=30, verbose_name='\u767b\u8bb0\u4eba')),
                ('line_signtime', models.DateField(auto_now_add=True, verbose_name='\u767b\u8bb0\u65f6\u95f4')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='node_address',
            field=models.CharField(max_length=255, verbose_name='\u8282\u70b9\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_contact',
            field=models.CharField(max_length=255, verbose_name='\u8054\u7cfb\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_name',
            field=models.CharField(max_length=255, verbose_name='\u8282\u70b9\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_signer',
            field=models.CharField(max_length=50, verbose_name='\u767b\u8bb0\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_signtime',
            field=models.DateField(auto_now_add=True, verbose_name='\u767b\u8bb0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('\u603b\u90e8', '\u603b\u90e8'), ('\u5206\u90e8', '\u5206\u90e8')], max_length=50, verbose_name='\u8282\u70b9\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='line',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.Node'),
        ),
    ]
