# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_auto_20160911_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='echo.Node'),
        ),
    ]
